apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trust-trustification-jbmw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trust-trustification-jbmw
    app.kubernetes.io/part-of: trustification-1
  name: trust-trustification-jbmw
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: trust-trustification-jbmw
status:
  loadBalancer: {}
